### ISSUE TITLE
PROXIMITY UUID

### ISSUE THREAD

**Issue by quelife** [daisuke-t-jp/BluetoothManager#1]
I want to add many PROXIMITY UUID to help me suggest ways or examples for me.

**Comment by daisuke-t-jp** [comment]
Sorry for late reply.

This library is created to target a single PROXIMITY UUID.

If you want to target multiple PROXIMITY UUIDs, you need to use [CLBeaconRegion](https://developer.apple.com/documentation/corelocation/clbeaconregion) directly.

I'm sorry I can not help you.

Thank you.
